/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  try {
    const { nodes, materials } = useGLTF('/models/Tree.glb')
    
    if (!nodes.Environment_PalmTree_3) {
      console.error('[Tree] Environment_PalmTree_3 node not found in GLTF')
      return (
        <group {...props} dispose={null}>
          <mesh>
            <boxGeometry args={[1, 3, 1]} />
            <meshStandardMaterial color="#27ae60" />
          </mesh>
        </group>
      )
    }
    
    return (
      <group {...props} dispose={null}>
        <mesh 
          geometry={nodes.Environment_PalmTree_3.geometry} 
          material={materials.Atlas} 
          scale={100}
        />
      </group>
    )
  } catch (error) {
    console.error('[Tree] Error loading tree model:', error)
    // Fallback to a simple green box
    return (
      <group {...props} dispose={null}>
        <mesh>
          <boxGeometry args={[1, 3, 1]} />
          <meshStandardMaterial color="#27ae60" />
        </mesh>
      </group>
    )
  }
}

useGLTF.preload('/models/Tree.glb')
